CREATE DATABASE IF NOT EXISTS contato DEFAULT CHARACTER SET utf8;
USE `contato`;

CREATE TABLE IF NOT EXISTS usuario (
    id_usuarios INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR (100) NULL,
    email VARCHAR (45) NULL,
    senha VARCHAR (32) NULL
);